Feat/refactoring retry
voyages-sncf-technologies/soda-test-service pull request #23
Opened 2020-10-15 09:54 UTC by MaximeJEUSS

- Make a Client without timeout and remove the retry when the request is a create session

2020-10-15 21:29 UTC, theredfish commented
@MaximeJEUSS  if the pull request is done you can remove the draft and ask for a review.

2020-10-16 14:53 UTC, theredfish requested changes

2020-10-16 14:53 UTC, theredfish commented on .gitignore
> +Makefile
Remove this and do not commit your own Makefile. This information isn't relevant in the context of this project. Not everybody will use a Makefile in local.

2020-10-16 14:53 UTC, theredfish commented on Cargo.toml
> +version = "0.3.3"
```suggestion
version = "0.3.1"
```

Not sure why you are patching 3 versions in one... If you already pushed a private version of the test-service with 2 other patches you will need to yank them and publish the `0.3.1` patch again.

2020-10-16 14:53 UTC, theredfish commented on README.md
> +  image: soda/test-service:0.3.3
same for the patch version

2020-10-16 14:53 UTC, theredfish commented on src/inspector.rs
> +pub fn is_a_new_create_session(method: Method, path: &str) -> bool {
Is there a case where the path can be exactly equals to `/wd/hub/session` while the HTTP method is different from `POST`? If not the case, `new_session()` already check this as explained by the documentation : 

```rust
/// Split the path to determine if it's a new session
/// (the path doesn't contain the session's id) or if it's
/// an existing session (the path contains the session's id).
/// If the head and the tail of the path are empty,
/// it's a new session event that we want to capture.
```

2020-10-16 14:53 UTC, theredfish commented on src/reverse_proxy.rs
> +            res => return res,
Maybe there is another way to handle the loop result : https://doc.rust-lang.org/stable/rust-by-example/flow_control/loop/return.html

2020-10-16 14:53 UTC, theredfish commented on src/reverse_proxy.rs
>  pub async fn send_request(
Concerning the retry, it's currently hard to follow what you written. I suggest you to :

- Put the retry logic in another module
- Or use an existing library :) https://docs.rs/retry/1.1.0/retry/

2020-10-16 14:53 UTC, theredfish commented on src/reverse_proxy.rs
> +    request_id: Uuid,
This additional information concerning the request makes me thing it could be better to use a structure instead of these arguments. Maybe something like :

```rust
struct CapturedRequest {
  method: Method,
  request_id: Uuid,
  body_bytes: Bytes, // maybe this can be optional so we can reuse the structure for requests with an empty body
  url: Url
}
```

2020-10-16 14:53 UTC, theredfish commented on src/reverse_proxy.rs
> +    info!("{:?} {} {}", request_id, method, path);
You can avoid the debug call (`{:?}`) by calling `request_id.to_string()` I think.

2020-10-16 14:53 UTC, theredfish commented on docker-compose.yml
> +    image: soda/test-service:0.3.3
same for the patch version

2020-10-29 10:35 UTC, MaximeJEUSS commented on src/inspector.rs
> +pub fn is_a_new_create_session(method: Method, path: &str) -> bool {
Indead

2020-10-29 11:01 UTC, MaximeJEUSS commented on src/reverse_proxy.rs
>  pub async fn send_request(
We tried an existing library but there was no good ones with the use of async/await functions.

2020-12-10 17:31 UTC, merged